### ISSUE TITLE
Entity class fails when no 'this; in question

### ISSUE THREAD

**Issue by CraigThorburn** [QAQA-land/qanta-codalab#7]
Fails when given sentence with no this

`test.add_sentence('asdflkjsdhflkaj')
Traceback (most recent call last):

  File "<ipython-input-7-1169dc87375a>", line 1, in <module>
    test.add_sentence('asdflkjsdhflkaj')

  File "D:/ubuntu/qanta-codalab/src/qanta/entity_recognizer.py", line 28, in add_sentence
    entity = self.get_entity(sentence)

  File "D:/ubuntu/qanta-codalab/src/qanta/entity_recognizer.py", line 22, in get_entity
    entity = word_tokenize(self._this_regex.search(sentence).group())[1]

AttributeError: 'NoneType' object has no attribute 'group'

**Comment by CraigThorburn** [comment]
Solved with entity merge
